config/routes.rb
LoggerViewer::Application.routes.draw do
  root :to => 'view_logs#index'
  match 'view_logs' => 'view_logs#index'
  match 'view_logs/dir' => 'view_logs#dir'
  match 'view_logs/log_file' => 'view_logs#log_file'
  match 'view_logs/down_log' => 'view_logs#down_log'
  
  root :to => 'view_logs#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  
end

app/controllers/view_logs_controller.rb
# encoding: UTF-8

class ViewLogsController < ApplicationController

  around_filter :verifi_log_path

  #列出所有的日志目录
  def index
  end


  #显示特定目录下的所有日志
  def dir
    @log_files = Dir.glob(File.join(@log_dir,"**")).map{|path| path if File.file?(path)}.delete_if{|v| v==nil}
    Rails.logger.debug { "*"*80  }
    Rails.logger.debug { @log_files }
  end

  #显示日志
  def log_file
    line = params[:line] || 20
    @grep = params[:grep]
    @line = line.to_i >= 200 ? 200 : line.to_i
    @after = params[:after].to_i || 0
    @before = params[:before].to_i || 0
    if @grep.to_s.strip.size > 0
      @log_lines = LogFile.egrep(@log_file,linenum:@line,regx:@grep,after:@after,before:@before)
    else
      @log_lines = LogFile.tail(@log_file,linenum:@line)
    end
  end

  # 下载日志文件
  def down_log
    send_file @log_file
  end

  private
  
  def clean_path(s)
    '' unless s
    s.gsub!(/'|"/,'')
    s.gsub!(/>+/,'')
    s.gsub!(/<+/,'')
    s.gsub!(/\|/,'')
    File.expand_path(s)
  end

  def verifi_log_path
    if _logdir = params[:logdir]
      @log_dir = clean_path(_logdir)
      Rails.logger.debug { "log_dir: #{@log_dir}" }
      raise RuntimeError.new("非法操作") unless LOG_DIR.include?(@log_dir)
    end

    if params[:logfile]
      @log_file = clean_path(params[:logfile])
      Rails.logger.debug { "log_file: #{@log_file}" }
      raise IOError.new("文件不存在") unless File.exists?(@log_file)
      raise RuntimeError.new("非法操作") unless LOG_DIR.include?(File.dirname(@log_file))
    end
    yield
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/view_logs_helper.rb
module ViewLogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoggerViewer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/layouts/application_frameset.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoggerViewer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<%= yield %>
</html>

app/views/view_logs/_dir_list.html.erb
<% LOG_DIR.each do |log_dir| %>
<%= link_to log_dir,view_logs_dir_url(logdir: log_dir)%>
<% end %>

app/views/view_logs/_form.html.erb
<form action="<%=view_logs_log_file_url%>" method="get">
  显示:<input type="text" name="line" value="<%=@line%>" size="4">行
  包含:<input type="text" name="grep" value="<%=@grep%>" size="50">
  前:<input type="text" name="before" value="<%=@before%>" size="3">行
  后:<input type="text" name="after" value="<%=@after%>" size="3">行
  <input type="submit" value="刷新">
  <input type="hidden" name="logfile" value="<%=@log_file%>">
  <input type="hidden" name="logdir" value="<%=@log_dir%>">
</form>

app/views/view_logs/dir.html.erb
<%=render 'dir_list'%>
<hr/>
<%@log_files.each do |log_file|%>
	<%= link_to log_file,view_logs_log_file_url(:logfile => log_file,:logdir => @log_dir)%> 
	<%= link_to 'down',view_logs_down_log_url(:logfile => log_file,:logdir => @log_dir)%> 
	<br/>
<%end%>

app/views/view_logs/index.html.erb
<%=render 'dir_list'%>

app/views/view_logs/log_file.html.erb
<%=render 'dir_list'%>
<hr/>

显示: <%=@log_file%> @ <%= link_to @log_dir,view_logs_dir_url(logdir: @log_dir)%>
<%= render 'form' %>

<pre class="logline">
<%@log_lines.each do |log_line| %>
  <%=log_line%>
<%end%>
</pre>

<%= render 'form' %>